# Generated by Django 5.2.5 on 2025-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo')], max_length=10),
        ),
    ]
