# Generated by Django 5.2.5 on 2025-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo'), ('PDF', 'PDF')], max_length=10),
        ),
    ]
