# Generated by Django 5.2.5 on 2025-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_lesson_file_lesson_content_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
