# Generated by Django 5.2.6 on 2025-09-17 12:17

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
