# Generated by Django 5.2.6 on 2025-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tag_remove_course_tags_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
