# Generated by Django 5.2.6 on 2025-09-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_course_tags_delete_tag_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags, e.g., Python,Django,Frontend', max_length=200),
        ),
    ]
