# Generated by Django 5.2.6 on 2025-09-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
    ]
