# Generated by Django 5.2.6 on 2025-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_lesson_pdf_file_alter_lesson_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
