# Generated by Django 5.2.6 on 2025-09-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_lesson_pdf_file_lesson_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
    ]
